export const RECEBER_INVESTIMENTOS = 'investimentos.RECEBER_INVESTIMENTOS';
export const CALCULAR_INVESTIMENTO = 'investimentos.CALCULAR_INVESTIMENTO';
export const INCLUIR_INVESTIMENTO = 'investimentos.INCLUIR_INVESTIMENTO';
export const ATUALIZAR_INVESTIMENTO = 'investimentos.ATUALIZAR_INVESTIMENTO';
export const EXCLUIR_INVESTIMENTO = 'investimentos.EXCLUIR_INVESTIMENTO';
export const ATUALIZAR_EVOLUCAO = 'investimentos.ATUALIZAR_EVOLUCAO';
export const RECEBER_INDEXADORES = 'investimentos.RECEBER_INDEXADORES';
export const RECEBER_INDICES = 'investimentos.RECEBER_INDICES';